name: '테스트'

on: 'push'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setting Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: yarn

      - name: Tests
        run: yarn run test

      - name: Type-check
        run: yarn run tsc
